import Head from "next/head";
import Image from "next/image";
import qrimage from "@/public/image-qr-code.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main>
        <div className="flex flex-col items-center justify-center h-screen w-screen">
          <div className="flex flex-col items-center justify-center bg-white rounded-xl p-3 w-64 gap-3">
            <Image src={qrimage} alt="qr-code" className="rounded-lg" />
            <p className="font-bold text-center text-dark-blue">
              Improve your front-end skills by building projects
            </p>
            <p className="text-xs text-grayish-blue text-center pb-5">
              Scan the QR code to visit Frontend Mentor and take your coding
              skills to the next level
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
